package com.boge.pojo;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.code
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.sex
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.note
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.code
	 * @return  the value of user.code
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.code
	 * @param code  the value for user.code
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.sex
	 * @return  the value of user.sex
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.sex
	 * @param sex  the value for user.sex
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.note
	 * @return  the value of user.note
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.note
	 * @param note  the value for user.note
	 * @mbggenerated  Fri Nov 20 15:49:52 CST 2015
	 */
	public void setNote(String note) {
		this.note = note;
	}
}